apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-go-web-app
  labels:
    app: devops-go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-go-web-app
  template:
    metadata:
      labels:
        app: devops-go-web-app
    spec:
      containers:
      - name: devops-go-web-app
        image: dhaneshshingade/devops-go-web-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
