apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops_go_web_app
spec:
  ingressClassName: nginx
  rules:
  - host: "devops_go_web_app.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: devops_go_web_app
            port:
              number: 80