apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-go-web-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "devops-go-web-app.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: devops-go-web-app
            port:
              number: 80