apiVersion: v1
kind: Service
metadata:
  name: devops_go_web_app
  labels:
    app: devops_go_web_app
spec:
  selector:
    app: devops_go_web_app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
