apiVersion: v1
kind: Service
metadata:
  name: devops-go-web-app
  labels:
    app: devops-go-web-app
spec:
  selector:
    app: devops-go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
